export const NEXT_PUBLIC_SERVICE_ID_EMAILJS= process.env.NEXT_PUBLIC_SERVICE_ID_EMAILJS || '';
export const NEXT_PUBLIC_TEMPLATE_ID_EMAILJS= process.env.NEXT_PUBLIC_TEMPLATE_ID_EMAILJS || '';
export const NEXT_PUBLIC_APIKEY_EMAILJS= process.env.NEXT_PUBLIC_APIKEY_EMAILJS || '';