export const NEXT_PUBLIC_SERVICE_ID_EMAILJS= process.env.NEXT_PUBLIC_SERVICE_ID_EMAILJS || '';
export const NEXT_PUBLIC_TEMPLATE_ID_EMAILJS= process.env.NEXT_PUBLIC_TEMPLATE_ID_EMAILJS || '';
export const NEXT_PUBLIC_APIKEY_EMAILJS= process.env.NEXT_PUBLIC_APIKEY_EMAILJS || '';
export const NEXT_PUBLIC_FACEBOOK= process.env.NEXT_PUBLIC_FACEBOOK || '';
export const NEXT_PUBLIC_INSTAGRAM= process.env.NEXT_PUBLIC_INSTAGRAM || '';
export const NEXT_PUBLIC_LINKEDIN= process.env.NEXT_PUBLIC_LINKEDIN || '';